import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6C6C6C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleHome: {
    justifyContent: 'center',
    textAlign: 'left',
    // flex: 1,
    color: '#DBDBDB',
    fontSize: 25,
    marginHorizontal: 10,
    marginBottom: 30,
    marginTop: 140,
  },
  ImgLogo: {
    position: 'absolute',
    width: 93,
    height: 82,
    left: 21,
    top: 35,
    borderRadius: 15,
  },
  search: {
    marginTop: 0,
  },
  TextLogo: {
    position: 'absolute',
    // width: 93,
    // height: 82,
    left: 120,
    top: 45,
    fontSize: 38,
    color: '#DBDBDB',
  },
  Button: {
    backgroundColor: '#04D361',
    borderRadius: 15,
    paddingLeft: 20,
    paddingRight: 20,
    paddingTop: 20,
    paddingBottom: 20,
    width: 200,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: '18%',
  },
  ViewButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewButtonAdmin: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 25,
  },
  ImgButton: {
    height: 45,
    width: 40,
  },
  textButton: {
    color: '#fff',
    fontFamily: 'Roboto',
    marginVertical: 0,
    marginHorizontal: 5,
  },
  containerRequest: {
    borderRadius: 8,
    height: 300,
    width: 300,
    color: '#3D3D4D',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: '#ffffff',
    marginBottom: 22,
    marginTop: 15,
    marginHorizontal: 8,
  },

});
export default styles;
